# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7efcdd0e5f74e3aa60aaee1354b1f8277f2348131ab96afd7159921ab333bfd97653410b307d8d3c23718f36c73544b174acbd49079f88b1ba1ed963e676efa3

test:
  secret_key_base: 939ca78f8b371eb60a5786197582090fe519bba362674993723f555475b4ec1d08e8d9c7a8cd0227d3c8e03764c26bed2d0c522444f890da49ed8c2d010c2003

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
